### ISSUE TITLE
Include OpenAPI endpoint 'summary' and 'description' 

### ISSUE THREAD

**Issue by nicoburniske** [golemcloud/golem-openapi-client-generator#18]
The openapi doc includes `summary` and `description` fields like this. We should add these as rustdoc to generated client code
```yaml
  /v1/projects/{project_id}/grants/{grant_id}:
    get:
      tags:
      - ProjectGrant
      summary: Get a specific grant of a project
      description: Returns a specific grant of a specific project. The returned object is the same as the elements of the grants endpoint's response described above.
```
